### ISSUE TITLE
核心库问题

### ISSUE THREAD

**Issue by eternallyjie** [weikaiyun/SFragmentation#10]
是否可以像fragmentation一样拆分一个fragmentationx-core核心库，supportActivity、supportFragment等由自己去实现呢？

**Comment by weikaiyun** [comment]
supportActivity、supportFragment现在一样可以自己实现呀，参照supportActivity、supportFragment实现ISupportFragment和ISupportActivity两个接口就好呀

**Comment by weikaiyun** [comment]
另外那个replaceFragment报错的问题， 请fork仓库，将demo推上去，我调试看看。

**Comment by eternallyjie** [comment]
> 另外那个replaceFragment报错的问题， 请fork仓库，将demo推上去，我调试看看。

好的。我去弄个demo看看。另外还有个问题，我在fragment里面使用startChild()无法打开页面。

**Comment by weikaiyun** [comment]
使用startChild首先得在fragment里面添加一个root child fragment

**Comment by eternallyjie** [comment]
> 使用startChild首先得在fragment里面添加一个root child fragment， 不能直接就startChild

但是当我使用start()方法打开页面的时候，返回的时候不是上一次的页面，而是loadMultipleRootFragment(int containerId, int showPosition, ISupportFragment... toFragments)方法中添加的最后一个fragment

**Comment by weikaiyun** [comment]
![image](https://user-images.githubusercontent.com/20124328/116017570-8ef78200-a672-11eb-817a-08e2fd994f57.png)
首先要调用这个。

**Comment by eternallyjie** [comment]
> ![image](https://user-images.githubusercontent.com/20124328/116017570-8ef78200-a672-11eb-817a-08e2fd994f57.png)
> 首先要调用这个。

那这样的话我所有的fragment都要loadRootFragment(),那我又何必调用startChild()ne ,直接代用start()放啊就好了啊

**Comment by weikaiyun** [comment]
你要把层级分清楚，你使用start的话， 所有的fragment由activity的fragmentmanager管理， 你使用startChild() fragment由fragment的fragmentmanager管理 两个不是一回事

**Comment by eternallyjie** [comment]
> 你要把层级分清楚，你使用start的话， 所有的fragment由activity的fragmentmanager管理， 你使用startChild() fragment由fragment的fragmentmanager管理 两个不是一回事

我知道层级问题不是一回事，但是我activity里面loadMultipleRootFragment()拥有多个同层级的fragment（fA、fB、fC），如果在这些fragment里面的fA使用start打开新的页面，实际上应该是fA打开的子页面fAA没问题吧，但是调用start方法打开，是使用activity的fragmentmanager打开的，这时候我如果在发AA返回的话，显示的就不是刚才打开fAA的fA，而是会变成activity里面多个同层级的fragment里面最后添加的一个fragment，fC。

如果使用startChild()方法的话，我需要在fA、fB、fC中使用loadRootFragment()方法加载根fragment，比如是fA1、fB1、fC1。这个时候我在fA1里面使用start()方法实际上是寻找他的上级的fragmentmanager的对吧。用来打开新的页面FAA，这个时候再fAA中返回会显示正确的页面fA1。

按照上面这两种形式来说startChild实际上的用途其实是类似横屏设置页面那种左面列表，右面详情的形式是吗？

**Comment by weikaiyun** [comment]
startChild实际上的用途其实是类似横屏设置页面那种左面列表，右面详情的形式.这个确实就是startChild的使用方式。大多数情况下其实是用不到startChild的。

**Comment by eternallyjie** [comment]
> startChild实际上的用途其实是类似横屏设置页面那种左面列表，右面详情的形式.这个确实就是startChild的使用方式。大多数情况下其实是用不到startChild的。

那么start打开的页面返回的时候显示的页面变成了上一层同级的最后一个fragment是什么造成的呢？

**Comment by weikaiyun** [comment]
activity里面loadMultipleRootFragment()一般不会直接调用，而是在activity里面先加载一个root Fragment， 然后在这个root fragment里面调用loadMultipleRootFragment 而且loadMultipleRootFragment添加的子fragment里面 一般不去直接调用start

而是使用_mActivity.start() 这样新开的fragment会与activity中的root fragment平级

**Comment by weikaiyun** [comment]
> > startChild实际上的用途其实是类似横屏设置页面那种左面列表，右面详情的形式.这个确实就是startChild的使用方式。大多数情况下其实是用不到startChild的。
> 
> 那么start打开的页面返回的时候显示的页面变成了上一层同级的最后一个fragment是什么造成的呢？

这是因为这个时候 你start一个fragment 其实是相当于又添加了一个fragment 这时activity里面实际上是4个fragment同级的 你这个时候 返回的话 会将最后添加的fragment的前一个fragment 也就是FC show出来

**Comment by eternallyjie** [comment]
> > > startChild实际上的用途其实是类似横屏设置页面那种左面列表，右面详情的形式.这个确实就是startChild的使用方式。大多数情况下其实是用不到startChild的。
> > 
> > 
> > 那么start打开的页面返回的时候显示的页面变成了上一层同级的最后一个fragment是什么造成的呢？
> 
> 这是因为这个时候 你start一个fragment 其实是相当于又添加了一个fragment 这时activity里面实际上是4个fragment同级的 你这个时候 返回的话 会将最后添加的fragment的前一个fragment 也就是FC show出来。框架内部的原理就是这样的。

那么实际上如果有页面需要打开下级页面的话，我就得使用loadRootFragment()来加载这个页面才能避免这个问题了

**Comment by eternallyjie** [comment]
> > > startChild实际上的用途其实是类似横屏设置页面那种左面列表，右面详情的形式.这个确实就是startChild的使用方式。大多数情况下其实是用不到startChild的。
> > 
> > 
> > 那么start打开的页面返回的时候显示的页面变成了上一层同级的最后一个fragment是什么造成的呢？
> 
> 这是因为这个时候 你start一个fragment 其实是相当于又添加了一个fragment 这时activity里面实际上是4个fragment同级的 你这个时候 返回的话 会将最后添加的fragment的前一个fragment 也就是FC show出来。框架内部的原理就是这样的。

如果框架能够记住上一次show的fragment，返回的时候再显示上次的fragment就好了

**Comment by weikaiyun** [comment]
正常来说 loadMultipleRootFragment 是处理 tab切换fragment的 不应该在这些fragment里面 再加载子fragment呀。你说的这个就是你的特殊业务了。你为啥一定要在  loadMultipleRootFragment加载的fragment里面 开启子fragment 有啥特殊的场景使用到吗 我觉得都是可以使用别的方式处理的吧。

**Comment by weikaiyun** [comment]
你可以看看demo的层级结构 是比较通用的做法

**Comment by eternallyjie** [comment]
> 正常来说 loadMultipleRootFragment 是处理 tab切换fragment的 不应该在这些fragment里面 再加载子fragment呀。你说的这个就是你的特殊业务了。你为啥一定要在 loadMultipleRootFragment加载的fragment里面 开启子fragment 有啥特殊的场景使用到吗 我觉得都是可以使用别的方式处理的吧。

确实有可能是特殊业务场景了吧。横屏的时候，左面是菜单列表，右面是详情，比如左面菜单有个订单列表，右面就是显示订单列表，然后点击右面列表的某个订单，就打开该订单的详情页面，但是左面的菜单列表是不变的。这个时候就是有问题的

**Comment by weikaiyun** [comment]
这个场景可以这么处理， 订单列表一开始就是加载在一个root fragment里面， 也就是 订单列表是一个子fragment，点击列表摸个订单直接start订单列表这个fragment start详情页就好呀

**Comment by eternallyjie** [comment]
> 这个场景可以这么处理， 订单列表一开始就是加载在一个root fragment里面， 也就是 订单列表是一个子fragment，点击列表某个订单， 在订单列表页直接start详情页就好呀

对啊，所以我说我所有的loadMultipleRootFragment加载的fragment都使用loadRootFragment再加载fargment

**Comment by weikaiyun** [comment]
另外也可以这样啊 你左边的菜单列表不变， 你可以不弄成fragment 直接一个view不好嘛

**Comment by eternallyjie** [comment]
> 另外也可以这样啊 你左边的菜单列表不变， 你可以不弄成fragment 直接一个view不好嘛 然后你的fragment管理就简单多了

我布局是这样的，一个activity里面左面列表是RV，右面使用loadMultipleRootFragment加载fragment的

**Comment by weikaiyun** [comment]
我很迷惑你的布局，你可以借个图上来看看么

**Comment by qinyang1018** [comment]
直接群里聊吧 这样效率有点低
@weikaiyun @eternallyjie
