### ISSUE TITLE
SupportFragment 中的_mActivity字段类型应该修改为ISupportActivity

### ISSUE THREAD

**Issue by mtzqc** [weikaiyun/SFragmentation#14]
当自定义Activity的是时候会报类型转换错误，且SupportFragmentDelegate的hasEnterAnimation也应该暴露出来

**Comment by weikaiyun** [comment]
有代码示例嘛  自定义Activity报类型转换错误

**Comment by mtzqc** [comment]
开始我只自定义Activity，发现SupportFragment中有SupportActivity 会强转错误
然后有copy了SupportFragment自定义，发现SupportFragmentDelegate的hasEnterAnimation只能同包名访问，
然后又新建类SupportFragmentDelegate的同报名的子类
public class MyFragmentDelegate extends SupportFragmentDelegate {

    public MyFragmentDelegate (ISupportFragment support) {
        super(support);
    }

    public boolean isEnterAnimation() {
        return hasEnterAnimation;
    }

    public void setEnterAnimation(boolean enter) {
        this.hasEnterAnimation = enter;
    }
}

**Comment by weikaiyun** [comment]
确实hasEnterAnimation需要暴露出来 我发个新包。
