### ISSUE TITLE
jitpack错误

### ISSUE THREAD

**Issue by qiushui95** [weikaiyun/SFragmentation#16]
readme 引入地址错误。
应该为com.github.weikaiyun.EasyFragmentation

**Comment by weikaiyun** [comment]
以前叫EasyFragmentation，现在改成SFragmentation了，你现在是引入不了吗？

**Comment by weikaiyun** [comment]
见1.8.2 之前1.8.1打包未成功

**Comment by qiushui95** [comment]
@weikaiyun 我拉那个back的没有成功,我看你readme  jitpack图标点进去是EasyFragmentation，你把那个图标地址改一下
