### ISSUE TITLE
How to make a fragment becomes root fragment

### ISSUE THREAD

**Issue by HuuNguyen312** [weikaiyun/SFragmentation#18]
Hi @weikaiyun 

The current back-stack is [A, B, C]
After I started D from C, I want to D is root fragment (A, B, C are removed or clear old backstack)
When I back press from D fragment -> the activity is killed.
Please help me solve it.

Thanks

**Comment by weikaiyun** [comment]
Call replaceFragment.
![image](https://user-images.githubusercontent.com/20124328/121791625-940e9180-cc1e-11eb-902a-363cb09da6cf.png)
