### ISSUE TITLE
依赖无法下载

### ISSUE THREAD

**Issue by eternallyjie** [weikaiyun/SFragmentation#19]
1.8.3版本无法下载

**Comment by weikaiyun** [comment]
我用demo试了，1.8.3可以同步。

**Comment by eternallyjie** [comment]
> 我用demo试了，1.8.3可以同步。

前两天确实不可以同步1.8.3，只能同步1.8.2。刚才试了一下可以同步1.8.3了。。。

**Comment by eternallyjie** [comment]
前两天是点进去jitPack连接看了，把SFragmentation改成了EasyFragmentation可以同步1.8.3。SFragmentation只能同步1.8.2
