### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by wj071842154** [weikaiyun/SFragmentation#23]
https://github.com/YoKeyword/Fragmentation中使用
loadRootFragment(R.id.fl_container, AfterLoanClientManagementRiskReportFragment.newInstance(entity.getCustId(), entity.getCustType()));
加载fragmengt，发现出现内存泄漏了
![微信图片_20211019113839](https://user-images.githubusercontent.com/34715269/137840059-4a4eb1aa-094f-4617-ad85-d94b1e74b6ed.jpg
![微信图片_20211019113839](https://user-images.githubusercontent.com/34715269/137840078-01361288-cd7b-4b05-8c79-fa43dcc3da0a.jpg)

**Comment by weikaiyun** [comment]
https://github.com/YoKeyword/Fragmentation 你是用的是这个库吗 这个库已经不维护啦
