### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by codersu007** [weikaiyun/SFragmentation#25]
![QQ图片20220311160307](https://user-images.githubusercontent.com/18433099/157826983-6d01a488-93c4-4775-95f0-444e2715d545.png)
能帮我看看这个问题吗?
目前我这边没复现,但是bugly上有收集到
从activity里面start(EvaluationDetailHomeFragment.newInstance(bean));

**Comment by weikaiyun** [comment]
activity 应该先loadroot吧 要不就是这个activity已经要销毁了
