### ISSUE TITLE
转场动画卡顿

### ISSUE THREAD

**Issue by lazh** [weikaiyun/SFragmentation#7]
动画卡顿很明显，测试了多次都是如此，做的动画效果也只是基本的位移动画

**Comment by weikaiyun** [comment]
你咋onVisible回调里面做业务处理，应该就好。

**Comment by weikaiyun** [comment]
fragment生命周期是这样的，一般会先调用onresume之后，再调用onCreateAnimation，然后进行转场动画。onVisible会在转场动画结束之后回调。
