### ISSUE TITLE
从左边滑动返回时，仅在左上部分生效的问题

### ISSUE THREAD

**Issue by a5778874** [weikaiyun/SFragmentation#8]
Demo中从左边滑动返回时，仅在左上部分生效，感觉和左中部的侧滑图标冲突的感觉，要使左中和左下部滑动也生效如何解决,
Android9 以上不行

**Comment by weikaiyun** [comment]
可以录个屏看看吗，你说的左中部的侧滑图标是指啥？

**Comment by weikaiyun** [comment]
我好像在我的三星note9上面复现了，我的手机上面是有个侧滑图标的，目前侧滑图标会优先响应。不过我试了这个侧滑图标是可以改变位置的。

**Comment by a5778874** [comment]
> 我好像在我的三星note9上面复现了，我的手机上面是有个侧滑图标的，目前侧滑图标会优先响应。不过我试了这个侧滑图标是可以改变位置的。

是的，是与系统的侧滑图标冲突了，我在Android9.0原生系统和华为Android10都有

**Comment by a5778874** [comment]
> > 我好像在我的三星note9上面复现了，我的手机上面是有个侧滑图标的，目前侧滑图标会优先响应。不过我试了这个侧滑图标是可以改变位置的。
> 
> 是的，是与系统的侧滑图标冲突了，我在Android9.0原生系统和华为Android10都有，但华为和原生Android系统侧滑图标我也找不到哪里改变位置

**Comment by weikaiyun** [comment]
我是长按这个侧滑图标可以上下移动，也可以移到右边，你可以试试
