### ISSUE TITLE
How to custom animator of Fragment

### ISSUE THREAD

**Issue by HuuNguyen312** [weikaiyun/SFragmentation#9]
Dear @weikaiyun 

In Fragmentation library of YoKey, I can override animator of fragment by the "onCreateFragmentAnimator" method.
But I can't find any similar function in your new library

**Comment by weikaiyun** [comment]
for the whole app, you can customize the animation like this:
![image](https://user-images.githubusercontent.com/20124328/109109906-1e66de80-7771-11eb-9dbb-fee4919c83c3.png)

for the activity, you can customize the animation by invoking "setFragmentAnimator"

for the fragment, you can customize the animation using "extraTransaction", you can find the usage in demo:
![image](https://user-images.githubusercontent.com/20124328/109110431-165b6e80-7772-11eb-9f0e-e36879ce8fc0.png)
